name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ruff lint
        uses: astral-sh/ruff-action@v3
        with:
          args: check .

      - name: Ruff format
        uses: astral-sh/ruff-action@v3
        with:
          args: format . --check

